spring:
  application:
    name: zuul
server:
  port: 9091
eureka:
  client:
    service-url:
      defaultZone: http://localhost:9090/eureka/
zuul:
  routes:
    csdn: /csdn/**
  ignored-patterns: /*-service/**
  #ignored-services: order-service
ribbon:
  ReadTimeout: 30000
  ConnectTimeout: 30000
