# database
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mycsdn?useSSL=false
    driver-class-name:  com.mysql.jdbc.Driver
    username: root
    password: 123456
  elasticsearch:
    jest:
      uris: http://127.0.0.1:9300
      read-timeout: 5000

mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
  type-aliases-package: com.example.entity

#showSql
logging:
  level:
    com:
      example:
        mapper : debug